apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        name: techtrends
        ports:
        - containerPort: {{ .Values.containers.ports.containerPort }}
        livenessProbe:
          httpGet:
            path: /healthz         # The path to check for the liveness probe
            port: {{ .Values.containers.ports.containerPort }}
          initialDelaySeconds: 15  # Wait this many seconds before starting the probe
          periodSeconds: 10        # Check the probe every 10 seconds
        readinessProbe:
          httpGet:
            path: /healthz         # The path to check for the readiness probe
            port: {{ .Values.containers.ports.containerPort }}             # The port to check on
          initialDelaySeconds: 5   # Wait this many seconds before starting the probe
          periodSeconds: 5  
        resources:
{{ toYaml .Values.resources | indent 12 }}
