apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
    tag: latest
  type: ClusterIP