namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: abhirupaec2022/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    cpu: 500m
    memory: 128Mi


containers:
  ports:
    containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz 

readinessProbe:
  httpGet:
    path: /healthz 

